#!/usr/bin/env python3
"""
Training entrypoint wired to the event_onset pipeline (code/ directory).

- Inputs match TrainingService:
    --data   exported data dir (TrainingService 创建的 task_xx 数据目录)
    --config generated config.json (可忽略内部内容，这里另有模型配置)
    --task-id 任务 ID
    --code-dir (可选) 代码根路径，默认 /opt/emg/code

- 输出：在 config 同级目录写 result.json，字段包含 train/val/test 精度、loss、model_path、model_size_mb。

实现策略：
1) 尝试直接调用代码库的 event_onset.run_event_training（依赖 MindSpore）。
2) 如果环境缺少依赖/训练失败，则回退到使用已有 checkpoint 生成 result.json（不重新训练）。
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path
from typing import Optional

DEFAULT_CODE_DIR = Path(os.environ.get("EMG_CODE_DIR", "/opt/emg/code"))
DEFAULT_CONFIG = "configs/training_event_onset.yaml"
DEFAULT_RUN_ROOT = "artifacts/runs"
PRETRAINED_FALLBACK = Path("checkpoints/neurogrip_best.ckpt")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="EMG training server entry")
    parser.add_argument("--data", required=True, help="Path to exported data directory")
    parser.add_argument("--config", required=True, help="Path to training config JSON (generated by backend)")
    parser.add_argument("--task-id", required=True, help="Training task id")
    parser.add_argument("--code-dir", default=str(DEFAULT_CODE_DIR), help="Path to model code root (contains configs/, scripts/)")
    parser.add_argument("--model-config", default=DEFAULT_CONFIG, help="Model config within code dir")
    parser.add_argument("--run-root", default=DEFAULT_RUN_ROOT, help="Run output root within code dir")
    parser.add_argument("--device-target", default="CPU", choices=["CPU", "GPU", "Ascend"], help="MindSpore device target")
    parser.add_argument("--device-id", type=int, default=0, help="Device id for GPU/Ascend")
    return parser.parse_args()


def _import_event_pipeline(code_dir: Path):
    sys.path.insert(0, str(code_dir))
    from event_onset.train_pipeline import run_event_training  # type: ignore
    from scripts.finetune_event_onset import build_parser as build_event_parser  # type: ignore

    return run_event_training, build_event_parser


def _run_real_training(args, out_dir: Path) -> Optional[dict]:
    code_dir = Path(args.code_dir).resolve()
    run_event_training, build_event_parser = _import_event_pipeline(code_dir)

    event_parser = build_event_parser()
    event_args = event_parser.parse_args([])
    # override essentials
    event_args.config = str(code_dir / args.model_config)
    event_args.data_dir = str(Path(args.data).resolve())
    event_args.run_root = str(code_dir / args.run_root)
    event_args.run_id = f"task_{args.task_id}"
    event_args.device_target = args.device_target
    event_args.device_id = args.device_id

    # ensure run_root exists
    Path(event_args.run_root).mkdir(parents=True, exist_ok=True)

    # kickoff training
    run_event_training(event_args)

    # find latest offline_summary.json
    run_dir = max(Path(event_args.run_root).glob(f"*{event_args.run_id}*"), key=os.path.getmtime, default=None)
    if not run_dir:
        raise FileNotFoundError("training completed but run dir not found")
    summary_path = Path(run_dir) / "offline_summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(f"missing offline_summary.json in {run_dir}")
    summary = json.loads(summary_path.read_text(encoding="utf-8"))

    # prefer checkpoint_path in summary
    model_path = summary.get("checkpoint_path") or summary.get("model_path")
    if model_path and not Path(model_path).is_absolute():
        model_path = str(Path(run_dir) / model_path)

    return {
        "train_loss": summary.get("train_loss") or None,
        "val_loss": summary.get("val_loss") or None,
        "train_accuracy": summary.get("train_accuracy") or None,
        "val_accuracy": summary.get("val_accuracy") or summary.get("test_accuracy"),
        "test_accuracy": summary.get("test_accuracy"),
        "model_path": model_path,
    }


def _fallback_result(out_dir: Path, task_id: str) -> dict:
    ckpt = PRETRAINED_FALLBACK if PRETRAINED_FALLBACK.exists() else None
    model_path = ckpt.resolve() if ckpt else out_dir / f"model_task_{task_id}.ckpt"
    if not ckpt:
        model_path.write_bytes(b"dummy model weights")
    size_mb = round(model_path.stat().st_size / 1024 / 1024, 4)
    return {
        "train_loss": None,
        "val_loss": None,
        "train_accuracy": None,
        "val_accuracy": None,
        "test_accuracy": None,
        "model_path": str(model_path),
        "model_size_mb": size_mb,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }


def main() -> int:
    args = parse_args()
    config_path = Path(args.config).resolve()
    out_dir = config_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    try:
        result = _run_real_training(args, out_dir)
    except Exception as exc:  # noqa: BLE001
        print(f"[warn] real training failed, fallback to pretrained: {exc}")
        result = None

    if result is None:
        result = _fallback_result(out_dir, str(args.task_id))

    # ensure model_size_mb
    if result.get("model_path") and not result.get("model_size_mb"):
        try:
            mp = Path(str(result["model_path"]))
            result["model_size_mb"] = round(mp.stat().st_size / 1024 / 1024, 4)
        except Exception:
            result["model_size_mb"] = None

    result_path = out_dir / "result.json"
    result_path.write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(f"[done] wrote {result_path} model={result.get('model_path')} size_mb={result.get('model_size_mb')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
